;*GdiplusEnums.h, GdiplusTypes.h, GdiplusInit.h, GdiplusPixelFormats.h, GdiplusColor.h, GdiplusMetaHeader.h, GdiplusImaging.h,
;GdiplusColorMatrix.h, GdiplusEffects.h

;ImageFormatUndefined GUID $b96b3ca9,$728,$11d3,<$9d,$7b,0,0,$f8,$1e,$f3,$2e>
;ImageFormatMemoryBMP GUID $b96b3caa,$728,$11d3,<$9d,$7b,0,0,$f8,$1e,$f3,$2e>
;ImageFormatBMP GUID $b96b3cab,$728,$11d3,<$9d,$7b,0,0,$f8,$1e,$f3,$2e>
;ImageFormatEMF GUID $b96b3cac,$728,$11d3,<$9d,$7b,0,0,$f8,$1e,$f3,$2e>
;ImageFormatWMF GUID $b96b3cad,$728,$11d3,<$9d,$7b,0,0,$f8,$1e,$f3,$2e>
;ImageFormatJPEG GUID $b96b3cae,$728,$11d3,<$9d,$7b,0,0,$f8,$1e,$f3,$2e>
;ImageFormatPNG GUID $b96b3caf,$728,$11d3,<$9d,$7b,0,0,$f8,$1e,$f3,$2e>
;ImageFormatGIF GUID $b96b3cb0,$728,$11d3,<$9d,$7b,0,0,$f8,$1e,$f3,$2e>
;ImageFormatTIFF GUID $b96b3cb1,$728,$11d3,<$9d,$7b,0,0,$f8,$1e,$f3,$2e>
;ImageFormatEXIF GUID $b96b3cb2,$728,$11d3,<$9d,$7b,0,0,$f8,$1e,$f3,$2e>
;ImageFormatIcon GUID $b96b3cb5,$728,$11d3,<$9d,$7b,0,0,$f8,$1e,$f3,$2e>
;FrameDimensionTime GUID $6aedbd6d,$3fb5,$418a,<$83,$a6,$7f,$45,$22,$9d,$c8,$72>
;FrameDimensionResolution GUID $84236f7b,$3bd3,$428f,<$8d,$ab,$4e,$a1,$43,$9c,$a3,$15>
;FrameDimensionPage GUID $7462dc86,$6180,$4c7e,<$8e,$3f,$ee,$73,$33,$a7,$a4,$83>
;FormatIDImageInformation GUID $e5836cbe,$5eef,$4f1d,<$ac,$de,$ae,$4c,$43,$b6,8,$ce>
;FormatIDJpegAppHeaders GUID $1c4afdcd,$6177,$43cf,<$ab,$c7,$5f,$51,$af,$39,$ee,$85>
;EncoderCompression GUID $e09d739d,$ccd4,$44ee,<$8e,$ba,$3f,$bf,$8b,$e4,$fc,$58>
;EncoderColorDepth GUID $66087055,$ad66,$4c7c,<$9a,$18,$38,$a2,$31,$b,$83,$37>
;EncoderScanMethod GUID $3a4e2661,$3109,$4e56,<$85,$36,$42,$c1,$56,$e7,$dc,$fa>
;EncoderVersion GUID $24d18c76,$814a,$41a4,<$bf,$53,$1c,$21,$9c,$cc,$f7,$97>
;EncoderRenderMethod GUID $6d42c53a,$229a,$4825,<$8b,$b7,$5c,$99,$e2,$b9,$a8,$b8>
;EncoderQuality GUID $1d5be4b5,$fa4a,$452d,<$9c,$dd,$5d,$b3,$51,$05,$e7,$eb>
;EncoderTransformation GUID $8d0eb2d1,$a58e,$4ea8,<$aa,$14,$10,$80,$74,$b7,$b6,$f9>
;EncoderLuminanceTable GUID $edb33bce,$266,$4a77,<$b9,4,$27,$21,$60,$99,$e7,$17>
;EncoderChrominanceTable GUID $f2e455dc,$9b3,$4316,<$82,$60,$67,$6a,$da,$32,$48,$1c>
;EncoderSaveFlag GUID $292266fc,$ac40,$47bf,<$8c,$fc,$a8,$5b,$89,$a6,$55,$de>
;EncoderColorSpace GUID $ae7a62a0,$ee2c,$49d8,<$9d,$7,$1b,$a8,$a9,$27,$59,$6e>
;EncoderImageItems GUID $63875e13,$1f1d,$45ab,<$91,$95,$a2,$9b,$60,$66,$a6,$50>
;EncoderSaveAsCMYK GUID $a219bbc9,$a9d,$4005,<$a3,$ee,$3a,$42,$1b,$8b,$b0,$6c>
;CodecIImageBytes GUID $25d1823,$6c7d,$447b,<$bb,$db,$a3,$cb,$c3,$df,$a2,$fc>
;BlurEffectGuid GUID $633c80a4, 0x1843, 0x482b, { 0x9e, 0xf2, 0xbe, 0x28, 0x34, 0xc5, 0xfd, 0xd4 } };
;SharpenEffectGuid GUID $63cbf3ee, 0xc526, 0x402c, { 0x8f, 0x71, 0x62, 0xc5, 0x40, 0xbf, 0x51, 0x42 } };
;ColorMatrixEffectGuid GUID $718f2615, 0x7933, 0x40e3, { 0xa5, 0x11, 0x5f, 0x68, 0xfe, 0x14, 0xdd, 0x74 } };
;ColorLUTEffectGuid GUID $a7ce72a9, 0xf7f, 0x40d7, { 0xb3, 0xcc, 0xd0, 0xc0, 0x2d, 0x5c, 0x32, 0x12 } };
;BrightnessContrastEffectGuid GUID $d3a1dbe1, 0x8ec4, 0x4c17, { 0x9f, 0x4c, 0xea, 0x97, 0xad, 0x1c, 0x34, 0x3d } };
;HueSaturationLightnessEffectGuid GUID $8b2dd6c3, 0xeb07, 0x4d87, { 0xa5, 0xf0, 0x71, 0x8, 0xe2, 0x6a, 0x9c, 0x5f } };
;LevelsEffectGuid GUID $99c354ec, 0x2a31, 0x4f3a, { 0x8c, 0x34, 0x17, 0xa8, 0x3, 0xb3, 0x3a, 0x25 } };
;TintEffectGuid GUID $1077af00, 0x2848, 0x4441, { 0x94, 0x89, 0x44, 0xad, 0x4c, 0x2d, 0x7a, 0x2c } };
;ColorBalanceEffectGuid GUID $537e597d, 0x251e, 0x48da, { 0x96, 0x64, 0x29, 0xca, 0x49, 0x6b, 0x70, 0xf8 } };
;RedEyeCorrectionEffectGuid GUID $74d29d05, 0x69a4, 0x4266, { 0x95, 0x49, 0x3c, 0xc5, 0x28, 0x36, 0xb6, 0x32 } };
;ColorCurveEffectGuid GUID $dd6a0022, 0x58e4, 0x4a67, { 0x9d, 0x9b, 0xd4, 0x8e, 0xb8, 0x81, 0xa5, 0x3d }

;Module Name:  GdiplusEnums.h
;Abstract:     GDI+ Enumeration Types

FlatnessDefault equ 0.25 ;1.0f/4.0f;

FillModeAlternate = 0
FillModeWinding = 1

QualityModeInvalid = -1
QualityModeDefault = 0
QualityModeLow = 1
QualityModeHigh = 2

CompositingModeSourceOver = 0
CompositingModeSourceCopy = 1

CompositingQualityInvalid = QualityModeInvalid
CompositingQualityDefault = QualityModeDefault
CompositingQualityHighSpeed = QualityModeLow
CompositingQualityHighQuality = QualityModeHigh
CompositingQualityGammaCorrected = 3
CompositingQualityAssumeLinear = 4

UnitWorld = 0
UnitDisplay = 1
UnitPixel = 2
UnitPoint = 3
UnitInch = 4
UnitDocument = 5
UnitMillimeter = 6
META_SETBKCOLOR = $201
META_SETBKMODE = $102
META_SETMAPMODE = $103
META_SETROP2 = $104
META_SETRELABS = $105
META_SETPOLYFILLMODE = $106
META_SETSTRETCHBLTMODE = $107
META_SETTEXTCHAREXTRA = $108
META_SETTEXTCOLOR = $209
META_SETTEXTJUSTIFICATION = $20A
META_SETWINDOWORG = $20B
META_SETWINDOWEXT = $20C
META_SETVIEWPORTORG = $20D
META_SETVIEWPORTEXT = $20E
META_OFFSETWINDOWORG = $20F
META_SCALEWINDOWEXT = $410
META_OFFSETVIEWPORTORG = $211
META_SCALEVIEWPORTEXT = $412
META_LINETO = $213
META_MOVETO = $214
META_EXCLUDECLIPRECT = $415
META_INTERSECTCLIPRECT = $416
META_ARC = $817
META_ELLIPSE = $418
META_FLOODFILL = $419
META_PIE = $81A
META_RECTANGLE = $41B
META_ROUNDRECT = $61C
META_PATBLT = $61D
META_SAVEDC = $01E
META_SETPIXEL = $41F
META_OFFSETCLIPRGN = $220
META_TEXTOUT = $521
META_BITBLT = $922
META_STRETCHBLT = $B23
META_POLYGON = $324
META_POLYLINE = $325
META_ESCAPE = $626
META_RESTOREDC = $127
META_FILLREGION = $228
META_FRAMEREGION = $429
META_INVERTREGION = $12A
META_PAINTREGION = $12B
META_SELECTCLIPREGION = $12C
META_SELECTOBJECT = $12D
META_SETTEXTALIGN = $12E
META_CHORD = $830
META_SETMAPPERFLAGS = $231
META_EXTTEXTOUT = $a32
META_SETDIBTODEV = $d33
META_SELECTPALETTE = $234
META_REALIZEPALETTE = $035
META_ANIMATEPALETTE = $436
META_SETPALENTRIES = $037
META_POLYPOLYGON = $538
META_RESIZEPALETTE = $139
META_DIBBITBLT = $940
META_DIBSTRETCHBLT = $b41
META_DIBCREATEPATTERNBRUSH   = $142
META_STRETCHDIB = $f43
META_EXTFLOODFILL = $548
META_SETLAYOUT = $149
META_DELETEOBJECT = $1f0
META_CREATEPALETTE = $0f7
META_CREATEPATTERNBRUSH = $1F9
META_CREATEPENINDIRECT = $2FA
META_CREATEFONTINDIRECT = $2FB
META_CREATEBRUSHINDIRECT = $2FC
META_CREATEREGION = $6FF

MetafileFrameUnitPixel = UnitPixel
MetafileFrameUnitPoint = UnitPoint
MetafileFrameUnitInch = UnitInch
MetafileFrameUnitDocument = UnitDocument
MetafileFrameUnitMillimeter = UnitMillimeter
MetafileFrameUnitGdi = 7
EMR_HEADER = 1
EMR_POLYBEZIER = 2
EMR_POLYGON = 3
EMR_POLYLINE = 4
EMR_POLYBEZIERTO = 5
EMR_POLYLINETO = 6
EMR_POLYPOLYLINE = 7
EMR_POLYPOLYGON = 8
EMR_SETWINDOWEXTEX = 9
EMR_SETWINDOWORGEX = 10
EMR_SETVIEWPORTEXTEX = 11
EMR_SETVIEWPORTORGEX = 12
EMR_SETBRUSHORGEX = 13
EMR_EOF = 14
EMR_SETPIXELV = 15
EMR_SETMAPPERFLAGS  = 16
EMR_SETMAPMODE = 17
EMR_SETBKMODE = 18
EMR_SETPOLYFILLMODE = 19
EMR_SETROP2 = 20
EMR_SETSTRETCHBLTMODE = 21
EMR_SETTEXTALIGN = 22
EMR_SETCOLORADJUSTMENT = 23
EMR_SETTEXTCOLOR  = 24
EMR_SETBKCOLOR = 25
EMR_OFFSETCLIPRGN = 26
EMR_MOVETOEX = 27
EMR_SETMETARGN = 28
EMR_EXCLUDECLIPRECT = 29
EMR_INTERSECTCLIPRECT = 30
EMR_SCALEVIEWPORTEXTEX = 31
EMR_SCALEWINDOWEXTEX = 32
EMR_SAVEDC = 33
EMR_RESTOREDC = 34
EMR_SETWORLDTRANSFORM = 35
EMR_MODIFYWORLDTRANSFORM = 36
EMR_SELECTOBJECT = 37
EMR_CREATEPEN = 38
EMR_CREATEBRUSHINDIRECT = 39
EMR_DELETEOBJECT  = 40
EMR_ANGLEARC = 41
EMR_ELLIPSE = 42
EMR_RECTANGLE = 43
EMR_ROUNDRECT = 44
EMR_ARC = 45
EMR_CHORD = 46
EMR_PIE = 47
EMR_SELECTPALETTE = 48
EMR_CREATEPALETTE = 49
EMR_SETPALETTEENTRIES = 50
EMR_RESIZEPALETTE = 51
EMR_REALIZEPALETTE = 52
EMR_EXTFLOODFILL   = 53
EMR_LINETO = 54
EMR_ARCTO = 55
EMR_POLYDRAW = 56
EMR_SETARCDIRECTION = 57
EMR_SETMITERLIMIT = 58
EMR_BEGINPATH = 59
EMR_ENDPATH = 60
EMR_CLOSEFIGURE = 61
EMR_FILLPATH = 62
EMR_STROKEANDFILLPATH = 63
EMR_STROKEPATH = 64
EMR_FLATTENPATH = 65
EMR_WIDENPATH = 66
EMR_SELECTCLIPPATH = 67
EMR_ABORTPATH = 68

EMR_GDICOMMENT = 70
EMR_FILLRGN = 71
EMR_FRAMERGN = 72
EMR_INVERTRGN = 73
EMR_PAINTRGN = 74
EMR_EXTSELECTCLIPRGN = 75
EMR_BITBLT = 76
EMR_STRETCHBLT = 77
EMR_MASKBLT = 78
EMR_PLGBLT = 79
EMR_SETDIBITSTODEVICE = 80
EMR_STRETCHDIBITS = 81
EMR_EXTCREATEFONTINDIRECTW = 82
EMR_EXTTEXTOUTA = 83
EMR_EXTTEXTOUTW = 84
EMR_POLYBEZIER16 = 85
EMR_POLYGON16 = 86
EMR_POLYLINE16 = 87
EMR_POLYBEZIERTO16 = 88
EMR_POLYLINETO16 = 89
EMR_POLYPOLYLINE16 = 90
EMR_POLYPOLYGON16 = 91
EMR_POLYDRAW16 = 92
EMR_CREATEMONOBRUSH = 93
EMR_CREATEDIBPATTERNBRUSHPT = 94
EMR_EXTCREATEPEN = 95
EMR_POLYTEXTOUTA = 96
EMR_POLYTEXTOUTW = 97

EMR_SETICMMODE = 98
EMR_CREATECOLORSPACE = 99
EMR_SETCOLORSPACE = 100
EMR_DELETECOLORSPACE = 101
EMR_GLSRECORD = 102
EMR_GLSBOUNDEDRECORD = 103
EMR_PIXELFORMAT = 104

EMR_RESERVED_105 = 105
EMR_RESERVED_106 = 106
EMR_RESERVED_107 = 107
EMR_RESERVED_108 = 108
EMR_RESERVED_109 = 109
EMR_RESERVED_110 = 110
EMR_COLORCORRECTPALETTE = 111
EMR_SETICMPROFILEA = 112
EMR_SETICMPROFILEW = 113
EMR_ALPHABLEND = 114
EMR_SETLAYOUT = 115
EMR_TRANSPARENTBLT = 116
EMR_RESERVED_117 = 117
EMR_GRADIENTFILL = 118
EMR_RESERVED_119 = 119
EMR_RESERVED_120 = 120
EMR_COLORMATCHTOTARGETW = 121
EMR_CREATECOLORSPACEW = 122
EMR_MIN = 1
EMR_MAX = 122

CoordinateSpaceWorld = 0
CoordinateSpacePage = 1
CoordinateSpaceDevice = 2

WrapModeTile = 0
WrapModeTileFlipX = 1
WrapModeTileFlipY = 2
WrapModeTileFlipXY = 3
WrapModeClamp = 4

HatchStyleHorizontal = 0
HatchStyleVertical = 1
HatchStyleForwardDiagonal = 2
HatchStyleBackwardDiagonal = 3
HatchStyleCross = 4
HatchStyleDiagonalCross = 5
HatchStyle05Percent = 6
HatchStyle10Percent = 7
HatchStyle20Percent = 8
HatchStyle25Percent = 9
HatchStyle30Percent = 10
HatchStyle40Percent = 11
HatchStyle50Percent = 12
HatchStyle60Percent = 13
HatchStyle70Percent = 14
HatchStyle75Percent = 15
HatchStyle80Percent = 16
HatchStyle90Percent = 17
HatchStyleLightDownwardDiagonal = 18
HatchStyleLightUpwardDiagonal = 19
HatchStyleDarkDownwardDiagonal = 20
HatchStyleDarkUpwardDiagonal = 21
HatchStyleWideDownwardDiagonal = 22
HatchStyleWideUpwardDiagonal = 23
HatchStyleLightVertical = 24
HatchStyleLightHorizontal = 25
HatchStyleNarrowVertical = 26
HatchStyleNarrowHorizontal = 27
HatchStyleDarkVertical = 28
HatchStyleDarkHorizontal = 29
HatchStyleDashedDownwardDiagonal = 30
HatchStyleDashedUpwardDiagonal = 31
HatchStyleDashedHorizontal = 32
HatchStyleDashedVertical = 33
HatchStyleSmallConfetti = 34
HatchStyleLargeConfetti = 35
HatchStyleZigZag = 36
HatchStyleWave = 37
HatchStyleDiagonalBrick = 38
HatchStyleHorizontalBrick = 39
HatchStyleWeave = 40
HatchStylePlaid = 41
HatchStyleDivot = 42
HatchStyleDottedGrid = 43
HatchStyleDottedDiamond = 44
HatchStyleShingle = 45
HatchStyleTrellis = 46
HatchStyleSphere = 47
HatchStyleSmallGrid = 48
HatchStyleSmallCheckerBoard = 49
HatchStyleLargeCheckerBoard = 50
HatchStyleOutlinedDiamond = 51
HatchStyleSolidDiamond = 52
HatchStyleTotal = 53
HatchStyleLargeGrid = HatchStyleCross
HatchStyleMin = HatchStyleHorizontal
HatchStyleMax = HatchStyleTotal - 1

DashStyleSolid = 0
DashStyleDash = 1
DashStyleDot = 2
DashStyleDashDot = 3
DashStyleDashDotDot = 4
DashStyleCustom = 5

DashCapFlat = 0
DashCapRound = 2
DashCapTriangle = 3

LineCapFlat = 0
LineCapSquare = 1
LineCapRound = 2
LineCapTriangle = 3
LineCapNoAnchor = $10
LineCapSquareAnchor = $11
LineCapRoundAnchor = $12
LineCapDiamondAnchor = $13
LineCapArrowAnchor = $14
LineCapCustom = $ff
LineCapAnchorMask = $f0

CustomLineCapTypeDefault = 0
CustomLineCapTypeAdjustableArrow = 1

LineJoinMiter = 0
LineJoinBevel = 1
LineJoinRound = 2
LineJoinMiterClipped = 3

PathPointTypeStart = 0
PathPointTypeLine = 1
PathPointTypeBezier = 3
PathPointTypePathTypeMask = 7
PathPointTypeDashMode = $10
PathPointTypePathMarker = $20
PathPointTypeCloseSubpath = $80
PathPointTypeBezier3 = 3

WarpModePerspective = 0
WarpModeBilinear = 1

LinearGradientModeHorizontal = 0
LinearGradientModeVertical = 1
LinearGradientModeForwardDiagonal = 2
LinearGradientModeBackwardDiagonal = 3

CombineModeReplace = 0
CombineModeIntersect = 1
CombineModeUnion = 2
CombineModeXor = 3
CombineModeExclude = 4
CombineModeComplement = 5

ImageTypeUnknown = 0
ImageTypeBitmap = 1
ImageTypeMetafile = 2

InterpolationModeInvalid = QualityModeInvalid
InterpolationModeDefault = QualityModeDefault
InterpolationModeLowQuality = QualityModeLow
InterpolationModeHighQuality = QualityModeHigh
InterpolationModeBilinear = 3
InterpolationModeBicubic = 4
InterpolationModeNearestNeighbor = 5
InterpolationModeHighQualityBilinear = 6
InterpolationModeHighQualityBicubic = 7

PenAlignmentCenter = 0
PenAlignmentInset = 1

BrushTypeSolidColor = 0
BrushTypeHatchFill = 1
BrushTypeTextureFill = 2
BrushTypePathGradient = 3
BrushTypeLinearGradient = 4

PenTypeSolidColor = BrushTypeSolidColor
PenTypeHatchFill = BrushTypeHatchFill
PenTypeTextureFill = BrushTypeTextureFill
PenTypePathGradient = BrushTypePathGradient
PenTypeLinearGradient = BrushTypeLinearGradient
PenTypeUnknown = -1

MatrixOrderPrepend = 0
MatrixOrderAppend = 1

GenericFontFamilySerif = 0
GenericFontFamilySansSerif = 1
GenericFontFamilyMonospace = 2

FontStyleRegular = 0
FontStyleBold = 1
FontStyleItalic = 2
FontStyleBoldItalic = 3
FontStyleUnderline = 4
FontStyleStrikeout = 8

SmoothingModeInvalid = QualityModeInvalid
SmoothingModeDefault = QualityModeDefault
SmoothingModeHighSpeed = QualityModeLow
SmoothingModeHighQuality = QualityModeHigh
SmoothingModeNone = 3
SmoothingModeAntiAlias = 4
SmoothingModeAntiAlias8x4 = SmoothingModeAntiAlias
SmoothingModeAntiAlias8x8 = 5

PixelOffsetModeInvalid = QualityModeInvalid
PixelOffsetModeDefault = QualityModeDefault
PixelOffsetModeHighSpeed = QualityModeLow
PixelOffsetModeHighQuality = QualityModeHigh
PixelOffsetModeNone = 3
PixelOffsetModeHalf = 4

TextRenderingHintSystemDefault = 0
TextRenderingHintSingleBitPerPixelGridFit = 1
TextRenderingHintSingleBitPerPixel = 2
TextRenderingHintAntiAliasGridFit = 3
TextRenderingHintAntiAlias = 4
TextRenderingHintClearTypeGridFit = 5

MetafileTypeInvalid = 0
MetafileTypeWmf = 1
MetafileTypeWmfPlaceable = 2
MetafileTypeEmf = 3
MetafileTypeEmfPlusOnly = 4
MetafileTypeEmfPlusDual = 5

EmfTypeEmfOnly	   = MetafileTypeEmf
EmfTypeEmfPlusOnly = MetafileTypeEmfPlusOnly
EmfTypeEmfPlusDual = MetafileTypeEmfPlusDual

ObjectTypeInvalid = 0
ObjectTypeBrush = 1
ObjectTypePen = 2
ObjectTypePath = 3
ObjectTypeRegion = 4
ObjectTypeImage = 5
ObjectTypeFont = 6
ObjectTypeStringFormat = 7
ObjectTypeImageAttributes = 8
ObjectTypeCustomLineCap = 9
ObjectTypeGraphics = 10
ObjectTypeMax = ObjectTypeGraphics
ObjectTypeMin = ObjectTypeBrush

GDIP_EMFPLUS_RECORD_BASE = $4000
GDIP_WMF_RECORD_BASE = $10000

WmfRecordTypeSetBkColor = GDIP_WMF_RECORD_BASE or META_SETBKCOLOR
WmfRecordTypeSetBkMode = GDIP_WMF_RECORD_BASE or META_SETBKMODE
WmfRecordTypeSetMapMode = GDIP_WMF_RECORD_BASE or META_SETMAPMODE
WmfRecordTypeSetROP2 = GDIP_WMF_RECORD_BASE or META_SETROP2
WmfRecordTypeSetRelAbs = GDIP_WMF_RECORD_BASE or META_SETRELABS
WmfRecordTypeSetPolyFillMode = GDIP_WMF_RECORD_BASE or META_SETPOLYFILLMODE
WmfRecordTypeSetStretchBltMode = GDIP_WMF_RECORD_BASE or META_SETSTRETCHBLTMODE
WmfRecordTypeSetTextCharExtra = GDIP_WMF_RECORD_BASE or META_SETTEXTCHAREXTRA
WmfRecordTypeSetTextColor = GDIP_WMF_RECORD_BASE or META_SETTEXTCOLOR
WmfRecordTypeSetTextJustification = GDIP_WMF_RECORD_BASE or META_SETTEXTJUSTIFICATION
WmfRecordTypeSetWindowOrg = GDIP_WMF_RECORD_BASE or META_SETWINDOWORG
WmfRecordTypeSetWindowExt = GDIP_WMF_RECORD_BASE or META_SETWINDOWEXT
WmfRecordTypeSetViewportOrg = GDIP_WMF_RECORD_BASE or META_SETVIEWPORTORG
WmfRecordTypeSetViewportExt = GDIP_WMF_RECORD_BASE or META_SETVIEWPORTEXT
WmfRecordTypeOffsetWindowOrg = GDIP_WMF_RECORD_BASE or META_OFFSETWINDOWORG
WmfRecordTypeScaleWindowExt = GDIP_WMF_RECORD_BASE or META_SCALEWINDOWEXT
WmfRecordTypeOffsetViewportOrg = GDIP_WMF_RECORD_BASE or META_OFFSETVIEWPORTORG
WmfRecordTypeScaleViewportExt = GDIP_WMF_RECORD_BASE or META_SCALEVIEWPORTEXT
WmfRecordTypeLineTo = GDIP_WMF_RECORD_BASE or META_LINETO
WmfRecordTypeMoveTo = GDIP_WMF_RECORD_BASE or META_MOVETO
WmfRecordTypeExcludeClipRect = GDIP_WMF_RECORD_BASE or META_EXCLUDECLIPRECT
WmfRecordTypeIntersectClipRect = GDIP_WMF_RECORD_BASE or META_INTERSECTCLIPRECT
WmfRecordTypeArc = GDIP_WMF_RECORD_BASE or META_ARC
WmfRecordTypeEllipse = GDIP_WMF_RECORD_BASE or META_ELLIPSE
WmfRecordTypeFloodFill = GDIP_WMF_RECORD_BASE or META_FLOODFILL
WmfRecordTypePie = GDIP_WMF_RECORD_BASE or META_PIE
WmfRecordTypeRectangle = GDIP_WMF_RECORD_BASE or META_RECTANGLE
WmfRecordTypeRoundRect = GDIP_WMF_RECORD_BASE or META_ROUNDRECT
WmfRecordTypePatBlt = GDIP_WMF_RECORD_BASE or META_PATBLT
WmfRecordTypeSaveDC = GDIP_WMF_RECORD_BASE or META_SAVEDC
WmfRecordTypeSetPixel = GDIP_WMF_RECORD_BASE or META_SETPIXEL
WmfRecordTypeOffsetClipRgn = GDIP_WMF_RECORD_BASE or META_OFFSETCLIPRGN
WmfRecordTypeTextOut = GDIP_WMF_RECORD_BASE or META_TEXTOUT
WmfRecordTypeBitBlt = GDIP_WMF_RECORD_BASE or META_BITBLT
WmfRecordTypeStretchBlt = GDIP_WMF_RECORD_BASE or META_STRETCHBLT
WmfRecordTypePolygon = GDIP_WMF_RECORD_BASE or META_POLYGON
WmfRecordTypePolyline = GDIP_WMF_RECORD_BASE or META_POLYLINE
WmfRecordTypeEscape = GDIP_WMF_RECORD_BASE or META_ESCAPE
WmfRecordTypeRestoreDC = GDIP_WMF_RECORD_BASE or META_RESTOREDC
WmfRecordTypeFillRegion = GDIP_WMF_RECORD_BASE or META_FILLREGION
WmfRecordTypeFrameRegion = GDIP_WMF_RECORD_BASE or META_FRAMEREGION
WmfRecordTypeInvertRegion = GDIP_WMF_RECORD_BASE or META_INVERTREGION
WmfRecordTypePaintRegion = GDIP_WMF_RECORD_BASE or META_PAINTREGION
WmfRecordTypeSelectClipRegion = GDIP_WMF_RECORD_BASE or META_SELECTCLIPREGION
WmfRecordTypeSelectObject = GDIP_WMF_RECORD_BASE or META_SELECTOBJECT
WmfRecordTypeSetTextAlign = GDIP_WMF_RECORD_BASE or META_SETTEXTALIGN
WmfRecordTypeDrawText = GDIP_WMF_RECORD_BASE or $62F
WmfRecordTypeChord = GDIP_WMF_RECORD_BASE or META_CHORD
WmfRecordTypeSetMapperFlags = GDIP_WMF_RECORD_BASE or META_SETMAPPERFLAGS
WmfRecordTypeExtTextOut = GDIP_WMF_RECORD_BASE or META_EXTTEXTOUT
WmfRecordTypeSetDIBToDev = GDIP_WMF_RECORD_BASE or META_SETDIBTODEV
WmfRecordTypeSelectPalette = GDIP_WMF_RECORD_BASE or META_SELECTPALETTE
WmfRecordTypeRealizePalette = GDIP_WMF_RECORD_BASE or META_REALIZEPALETTE
WmfRecordTypeAnimatePalette = GDIP_WMF_RECORD_BASE or META_ANIMATEPALETTE
WmfRecordTypeSetPalEntries = GDIP_WMF_RECORD_BASE or META_SETPALENTRIES
WmfRecordTypePolyPolygon = GDIP_WMF_RECORD_BASE or META_POLYPOLYGON
WmfRecordTypeResizePalette = GDIP_WMF_RECORD_BASE or META_RESIZEPALETTE
WmfRecordTypeDIBBitBlt = GDIP_WMF_RECORD_BASE or META_DIBBITBLT
WmfRecordTypeDIBStretchBlt = GDIP_WMF_RECORD_BASE or META_DIBSTRETCHBLT
WmfRecordTypeDIBCreatePatternBrush = GDIP_WMF_RECORD_BASE or META_DIBCREATEPATTERNBRUSH
WmfRecordTypeStretchDIB = GDIP_WMF_RECORD_BASE or META_STRETCHDIB
WmfRecordTypeExtFloodFill = GDIP_WMF_RECORD_BASE or META_EXTFLOODFILL
WmfRecordTypeSetLayout = GDIP_WMF_RECORD_BASE or $149
WmfRecordTypeResetDC = GDIP_WMF_RECORD_BASE or $14C
WmfRecordTypeStartDoc = GDIP_WMF_RECORD_BASE or $14D
WmfRecordTypeStartPage = GDIP_WMF_RECORD_BASE or $4F
WmfRecordTypeEndPage = GDIP_WMF_RECORD_BASE or $50
WmfRecordTypeAbortDoc = GDIP_WMF_RECORD_BASE or $52
WmfRecordTypeEndDoc = GDIP_WMF_RECORD_BASE or $5E
WmfRecordTypeDeleteObject = GDIP_WMF_RECORD_BASE or META_DELETEOBJECT
WmfRecordTypeCreatePalette = GDIP_WMF_RECORD_BASE or META_CREATEPALETTE
WmfRecordTypeCreateBrush = GDIP_WMF_RECORD_BASE or $F8
WmfRecordTypeCreatePatternBrush = GDIP_WMF_RECORD_BASE or META_CREATEPATTERNBRUSH
WmfRecordTypeCreatePenIndirect = GDIP_WMF_RECORD_BASE or META_CREATEPENINDIRECT
WmfRecordTypeCreateFontIndirect = GDIP_WMF_RECORD_BASE or META_CREATEFONTINDIRECT
WmfRecordTypeCreateBrushIndirect = GDIP_WMF_RECORD_BASE or META_CREATEBRUSHINDIRECT
WmfRecordTypeCreateBitmapIndirect = GDIP_WMF_RECORD_BASE or $2FD
WmfRecordTypeCreateBitmap = GDIP_WMF_RECORD_BASE or $6FE
WmfRecordTypeCreateRegion = GDIP_WMF_RECORD_BASE or META_CREATEREGION

EmfRecordTypeHeader = EMR_HEADER
EmfRecordTypePolyBezier = EMR_POLYBEZIER
EmfRecordTypePolygon = EMR_POLYGON
EmfRecordTypePolyline = EMR_POLYLINE
EmfRecordTypePolyBezierTo = EMR_POLYBEZIERTO
EmfRecordTypePolyLineTo = EMR_POLYLINETO
EmfRecordTypePolyPolyline = EMR_POLYPOLYLINE
EmfRecordTypePolyPolygon = EMR_POLYPOLYGON
EmfRecordTypeSetWindowExtEx = EMR_SETWINDOWEXTEX
EmfRecordTypeSetWindowOrgEx = EMR_SETWINDOWORGEX
EmfRecordTypeSetViewportExtEx = EMR_SETVIEWPORTEXTEX
EmfRecordTypeSetViewportOrgEx = EMR_SETVIEWPORTORGEX
EmfRecordTypeSetBrushOrgEx = EMR_SETBRUSHORGEX
EmfRecordTypeEOF = EMR_EOF
EmfRecordTypeSetPixelV = EMR_SETPIXELV
EmfRecordTypeSetMapperFlags = EMR_SETMAPPERFLAGS
EmfRecordTypeSetMapMode = EMR_SETMAPMODE
EmfRecordTypeSetBkMode = EMR_SETBKMODE
EmfRecordTypeSetPolyFillMode = EMR_SETPOLYFILLMODE
EmfRecordTypeSetROP2 = EMR_SETROP2
EmfRecordTypeSetStretchBltMode = EMR_SETSTRETCHBLTMODE
EmfRecordTypeSetTextAlign = EMR_SETTEXTALIGN
EmfRecordTypeSetColorAdjustment = EMR_SETCOLORADJUSTMENT
EmfRecordTypeSetTextColor = EMR_SETTEXTCOLOR
EmfRecordTypeSetBkColor = EMR_SETBKCOLOR
EmfRecordTypeOffsetClipRgn = EMR_OFFSETCLIPRGN
EmfRecordTypeMoveToEx = EMR_MOVETOEX
EmfRecordTypeSetMetaRgn = EMR_SETMETARGN
EmfRecordTypeExcludeClipRect = EMR_EXCLUDECLIPRECT
EmfRecordTypeIntersectClipRect = EMR_INTERSECTCLIPRECT
EmfRecordTypeScaleViewportExtEx = EMR_SCALEVIEWPORTEXTEX
EmfRecordTypeScaleWindowExtEx = EMR_SCALEWINDOWEXTEX
EmfRecordTypeSaveDC = EMR_SAVEDC
EmfRecordTypeRestoreDC = EMR_RESTOREDC
EmfRecordTypeSetWorldTransform = EMR_SETWORLDTRANSFORM
EmfRecordTypeModifyWorldTransform = EMR_MODIFYWORLDTRANSFORM
EmfRecordTypeSelectObject = EMR_SELECTOBJECT
EmfRecordTypeCreatePen = EMR_CREATEPEN
EmfRecordTypeCreateBrushIndirect = EMR_CREATEBRUSHINDIRECT
EmfRecordTypeDeleteObject = EMR_DELETEOBJECT
EmfRecordTypeAngleArc = EMR_ANGLEARC
EmfRecordTypeEllipse = EMR_ELLIPSE
EmfRecordTypeRectangle = EMR_RECTANGLE
EmfRecordTypeRoundRect = EMR_ROUNDRECT
EmfRecordTypeArc = EMR_ARC
EmfRecordTypeChord = EMR_CHORD
EmfRecordTypePie = EMR_PIE
EmfRecordTypeSelectPalette = EMR_SELECTPALETTE
EmfRecordTypeCreatePalette = EMR_CREATEPALETTE
EmfRecordTypeSetPaletteEntries = EMR_SETPALETTEENTRIES
EmfRecordTypeResizePalette = EMR_RESIZEPALETTE
EmfRecordTypeRealizePalette = EMR_REALIZEPALETTE
EmfRecordTypeExtFloodFill = EMR_EXTFLOODFILL
EmfRecordTypeLineTo = EMR_LINETO
EmfRecordTypeArcTo = EMR_ARCTO
EmfRecordTypePolyDraw = EMR_POLYDRAW
EmfRecordTypeSetArcDirection = EMR_SETARCDIRECTION
EmfRecordTypeSetMiterLimit = EMR_SETMITERLIMIT
EmfRecordTypeBeginPath = EMR_BEGINPATH
EmfRecordTypeEndPath = EMR_ENDPATH
EmfRecordTypeCloseFigure = EMR_CLOSEFIGURE
EmfRecordTypeFillPath = EMR_FILLPATH
EmfRecordTypeStrokeAndFillPath = EMR_STROKEANDFILLPATH
EmfRecordTypeStrokePath = EMR_STROKEPATH
EmfRecordTypeFlattenPath = EMR_FLATTENPATH
EmfRecordTypeWidenPath = EMR_WIDENPATH
EmfRecordTypeSelectClipPath = EMR_SELECTCLIPPATH
EmfRecordTypeAbortPath = EMR_ABORTPATH
EmfRecordTypeReserved_069 = 69
EmfRecordTypeGdiComment = EMR_GDICOMMENT
EmfRecordTypeFillRgn = EMR_FILLRGN
EmfRecordTypeFrameRgn = EMR_FRAMERGN
EmfRecordTypeInvertRgn = EMR_INVERTRGN
EmfRecordTypePaintRgn = EMR_PAINTRGN
EmfRecordTypeExtSelectClipRgn = EMR_EXTSELECTCLIPRGN
EmfRecordTypeBitBlt = EMR_BITBLT
EmfRecordTypeStretchBlt = EMR_STRETCHBLT
EmfRecordTypeMaskBlt = EMR_MASKBLT
EmfRecordTypePlgBlt = EMR_PLGBLT
EmfRecordTypeSetDIBitsToDevice = EMR_SETDIBITSTODEVICE
EmfRecordTypeStretchDIBits = EMR_STRETCHDIBITS
EmfRecordTypeExtCreateFontIndirect = EMR_EXTCREATEFONTINDIRECTW
EmfRecordTypeExtTextOutA = EMR_EXTTEXTOUTA
EmfRecordTypeExtTextOutW = EMR_EXTTEXTOUTW
EmfRecordTypePolyBezier16 = EMR_POLYBEZIER16
EmfRecordTypePolygon16 = EMR_POLYGON16
EmfRecordTypePolyline16 = EMR_POLYLINE16
EmfRecordTypePolyBezierTo16 = EMR_POLYBEZIERTO16
EmfRecordTypePolylineTo16 = EMR_POLYLINETO16
EmfRecordTypePolyPolyline16 = EMR_POLYPOLYLINE16
EmfRecordTypePolyPolygon16 = EMR_POLYPOLYGON16
EmfRecordTypePolyDraw16 = EMR_POLYDRAW16
EmfRecordTypeCreateMonoBrush = EMR_CREATEMONOBRUSH
EmfRecordTypeCreateDIBPatternBrushPt = EMR_CREATEDIBPATTERNBRUSHPT
EmfRecordTypeExtCreatePen = EMR_EXTCREATEPEN
EmfRecordTypePolyTextOutA = EMR_POLYTEXTOUTA
EmfRecordTypePolyTextOutW = EMR_POLYTEXTOUTW
EmfRecordTypeSetICMMode = 98
EmfRecordTypeCreateColorSpace = 99
EmfRecordTypeSetColorSpace = 100
EmfRecordTypeDeleteColorSpace = 101
EmfRecordTypeGLSRecord = 102
EmfRecordTypeGLSBoundedRecord = 103
EmfRecordTypePixelFormat = 104
EmfRecordTypeDrawEscape = 105
EmfRecordTypeExtEscape = 106
EmfRecordTypeStartDoc = 107
EmfRecordTypeSmallTextOut = 108
EmfRecordTypeForceUFIMapping = 109
EmfRecordTypeNamedEscape = 110
EmfRecordTypeColorCorrectPalette = 111
EmfRecordTypeSetICMProfileA = 112
EmfRecordTypeSetICMProfileW = 113
EmfRecordTypeAlphaBlend = 114
EmfRecordTypeSetLayout = 115
EmfRecordTypeTransparentBlt = 116
EmfRecordTypeReserved_117 = 117
EmfRecordTypeGradientFill = 118
EmfRecordTypeSetLinkedUFIs = 119
EmfRecordTypeSetTextJustification = 120
EmfRecordTypeColorMatchToTargetW = 121
EmfRecordTypeCreateColorSpaceW = 122
EmfRecordTypeMax = 122
EmfRecordTypeMin = 1

EmfPlusRecordTypeInvalid = GDIP_EMFPLUS_RECORD_BASE
EmfPlusRecordTypeHeader = $4001
EmfPlusRecordTypeEndOfFile = $4002
EmfPlusRecordTypeComment = $4003
EmfPlusRecordTypeGetDC = $4004
EmfPlusRecordTypeMultiFormatStart = $4005
EmfPlusRecordTypeMultiFormatSection = $4006
EmfPlusRecordTypeMultiFormatEnd = $4007
EmfPlusRecordTypeObject = $4008
EmfPlusRecordTypeClear = $4009
EmfPlusRecordTypeFillRects = $400a
EmfPlusRecordTypeDrawRects = $400b
EmfPlusRecordTypeFillPolygon = $400c
EmfPlusRecordTypeDrawLines = $400d
EmfPlusRecordTypeFillEllipse = $400e
EmfPlusRecordTypeDrawEllipse = $400f
EmfPlusRecordTypeFillPie = $4010
EmfPlusRecordTypeDrawPie = $4011
EmfPlusRecordTypeDrawArc = $4012
EmfPlusRecordTypeFillRegion = $4013
EmfPlusRecordTypeFillPath = $4014
EmfPlusRecordTypeDrawPath = $4015
EmfPlusRecordTypeFillClosedCurve = $4016
EmfPlusRecordTypeDrawClosedCurve = $4017
EmfPlusRecordTypeDrawCurve = $4018
EmfPlusRecordTypeDrawBeziers = $4019
EmfPlusRecordTypeDrawImage = $401a
EmfPlusRecordTypeDrawImagePoints = $401b
EmfPlusRecordTypeDrawString = $401c
EmfPlusRecordTypeSetRenderingOrigin = $401d
EmfPlusRecordTypeSetAntiAliasMode = $401e
EmfPlusRecordTypeSetTextRenderingHint = $401f
EmfPlusRecordTypeSetTextContrast = $4020
EmfPlusRecordTypeSetInterpolationMode = $4021
EmfPlusRecordTypeSetPixelOffsetMode = $4022
EmfPlusRecordTypeSetCompositingMode = $4023
EmfPlusRecordTypeSetCompositingQuality = $4024
EmfPlusRecordTypeSave = $4025
EmfPlusRecordTypeRestore = $4026
EmfPlusRecordTypeBeginContainer = $4027
EmfPlusRecordTypeBeginContainerNoParams = $4028
EmfPlusRecordTypeEndContainer = $4029
EmfPlusRecordTypeSetWorldTransform = $402a
EmfPlusRecordTypeResetWorldTransform = $402b
EmfPlusRecordTypeMultiplyWorldTransform = $402c
EmfPlusRecordTypeTranslateWorldTransform = $402d
EmfPlusRecordTypeScaleWorldTransform = $402e
EmfPlusRecordTypeRotateWorldTransform = $402f
EmfPlusRecordTypeSetPageTransform = $4030
EmfPlusRecordTypeResetClip = $4031
EmfPlusRecordTypeSetClipRect = $4032
EmfPlusRecordTypeSetClipPath = $4033
EmfPlusRecordTypeSetClipRegion = $4034
EmfPlusRecordTypeOffsetClip = $4035
EmfPlusRecordTypeDrawDriverString = $4036
EmfPlusRecordTypeStrokeFillPath = $4037
EmfPlusRecordTypeSerializableObject = $4038
EmfPlusRecordTypeSetTSGraphics = $4039
EmfPlusRecordTypeSetTSClip = $403a
EmfPlusRecordTotal = $403a
EmfPlusRecordTypeMax = EmfPlusRecordTotal - 1
EmfPlusRecordTypeMin = EmfPlusRecordTypeHeader

StringFormatFlagsDirectionRightToLeft = 1
StringFormatFlagsDirectionVertical = 2
StringFormatFlagsNoFitBlackBox = 4
StringFormatFlagsDisplayFormatControl = $20
StringFormatFlagsNoFontFallback = $400
StringFormatFlagsMeasureTrailingSpaces = $800
StringFormatFlagsNoWrap = $1000
StringFormatFlagsLineLimit = $2000
StringFormatFlagsNoClip = $4000
StringFormatFlagsBypassGDI = $80000000

StringTrimmingNone = 0
StringTrimmingCharacter = 1
StringTrimmingWord = 2
StringTrimmingEllipsisCharacter = 3
StringTrimmingEllipsisWord = 4
StringTrimmingEllipsisPath = 5

StringDigitSubstituteUser = 0
StringDigitSubstituteNone = 1
StringDigitSubstituteNational = 2
StringDigitSubstituteTraditional = 3

HotkeyPrefixNone = 0
HotkeyPrefixShow = 1
HotkeyPrefixHide = 2

StringAlignmentNear = 0
StringAlignmentCenter = 1
StringAlignmentFar = 2

DriverStringOptionsCmapLookup = 1
DriverStringOptionsVertical = 2
DriverStringOptionsRealizedAdvance = 4
DriverStringOptionsLimitSubpixel = 8

FlushIntentionFlush = 0
FlushIntentionSync = 1

EncoderParameterValueTypeByte = 1
EncoderParameterValueTypeASCII = 2
EncoderParameterValueTypeShort = 3
EncoderParameterValueTypeLong = 4
EncoderParameterValueTypeRational = 5
EncoderParameterValueTypeLongRange = 6
EncoderParameterValueTypeUndefined = 7
EncoderParameterValueTypeRationalRange	= 8
EncoderParameterValueTypePointer = 9

EncoderValueColorTypeCMYK = 0
EncoderValueColorTypeYCCK = 1
EncoderValueCompressionLZW = 2
EncoderValueCompressionCCITT3 = 3
EncoderValueCompressionCCITT4 = 4
EncoderValueCompressionRle = 5
EncoderValueCompressionNone = 6
EncoderValueScanMethodInterlaced = 7
EncoderValueScanMethodNonInterlaced = 8
EncoderValueVersionGif87 = 9
EncoderValueVersionGif89 = 10
EncoderValueRenderProgressive = 11
EncoderValueRenderNonProgressive = 12
EncoderValueTransformRotate90 = 13
EncoderValueTransformRotate180 = 14
EncoderValueTransformRotate270 = 15
EncoderValueTransformFlipHorizontal = 16
EncoderValueTransformFlipVertical = 17
EncoderValueMultiFrame = 18
EncoderValueLastFrame = 19
EncoderValueFlush = 20
EncoderValueFrameDimensionTime = 21
EncoderValueFrameDimensionResolution = 22
EncoderValueFrameDimensionPage = 23
EncoderValueColorTypeGray = 24
EncoderValueColorTypeRGB = 25

EmfToWmfBitsFlagsDefault = 0
EmfToWmfBitsFlagsEmbedEmf = 1
EmfToWmfBitsFlagsIncludePlaceable = 2
EmfToWmfBitsFlagsNoXORClip = 4

EmfToWmfBitsFlagsDefault = 0
EmfToWmfBitsFlagsEmbedEmf = 1
EmfToWmfBitsFlagsIncludePlaceable = 2
EmfToWmfBitsFlagsNoXORClip = 4

TestControlForceBilinear = 0
TestControlNoICM = 1
TestControlGetBuildNumber = 2

;Module Name:  GdiplusTypes.h
;Abstract:     GDI+ Types

REAL_MAX equ 3.402823466e+38
REAL_MIN equ 1.175494351e-38
REAL_TOLERANCE equ 1.175494351e-36
REAL_EPSILON equ 1.192092896e-07

Ok = 0
GenericError = 1
InvalidParameter = 2
OutOfMemory = 3
ObjectBusy = 4
InsufficientBuffer = 5
NotImplemented = 6
Win32Error = 7
WrongState = 8
Aborted = 9
FileNotFound = 10
ValueOverflow = 11
AccessDenied = 12
UnknownImageFormat = 13
FontFamilyNotFound = 14
FontStyleNotFound = 15
NotTrueTypeFont = 16
UnsupportedGdiplusVersion = 17
GdiplusNotInitialized = 18
PropertyNotFound = 19
PropertyNotSupported = 20
ProfileNotFound = 21

;Module Name:  Gdiplus initialization
;Abstract:     GDI+ Startup and Shutdown APIs

DebugEventLevelFatal = 0
DebugEventLevelWarning = 1

struct GdiplusStartupInput ;1, NULL, FALSE, FALSE
       GdiplusVersion dd ?,?
       DebugEventProc dq ?
       SuppressBackgroundThread dd ?
       SuppressExternalCodecs dd ?
ends

struct GdiplusStartupInputEx ;2, NULL, FALSE, FALSE, NULL
       GdiplusVersion dd ?,?
       DebugEventProc dq ?
       SuppressBackgroundThread dd ?
       SuppressExternalCodecs dd ?
       StartupParameters dd ?
ends

GdiplusStartupDefault = 0
GdiplusStartupNoSetRound = 1
GdiplusStartupSetPSValue = 2
GdiplusStartupTransparencyMask = $ff000000

struct GdiplusStartupOutput
       NotificationHook dd ?
       NotificationUnhook dd ?
ends

;Module Name:  Gdiplus Pixel Formats
;Abstract:     GDI+ Pixel Formats

ALPHA_SHIFT = 24
RED_SHIFT = 16
GREEN_SHIFT = 8
BLUE_SHIFT0 = 0
ALPHA_MASK = ($ff shl ALPHA_SHIFT)

PixelFormatIndexed = $10000
PixelFormatGDI = $20000
PixelFormatAlpha = $40000
PixelFormatPAlpha = $80000
PixelFormatExtended = $100000
PixelFormatCanonical = $200000

PixelFormatUndefined = 0
PixelFormatDontCare = 0

PixelFormat1bppIndexed = (1 or (1 shl 8) or PixelFormatIndexed or PixelFormatGDI)
PixelFormat4bppIndexed = (2 or (4 shl 8) or PixelFormatIndexed or PixelFormatGDI)
PixelFormat8bppIndexed = (3 or (8 shl 8) or PixelFormatIndexed or PixelFormatGDI)
PixelFormat16bppGrayScale = (4 or (16 shl 8) or PixelFormatExtended)
PixelFormat16bppRGB555 = (5 or (16 shl 8) or PixelFormatGDI)
PixelFormat16bppRGB565 = (6 or (16 shl 8) or PixelFormatGDI)
PixelFormat16bppARGB1555 = (7 or (16 shl 8) or PixelFormatAlpha or PixelFormatGDI)
PixelFormat24bppRGB = (8 or (24 shl 8) or PixelFormatGDI)
PixelFormat32bppRGB = (9 or (32 shl 8) or PixelFormatGDI)
PixelFormat32bppARGB = (10 or (32 shl 8) or PixelFormatAlpha or PixelFormatGDI or PixelFormatCanonical)
PixelFormat32bppPARGB = (11 or (32 shl 8) or PixelFormatAlpha or PixelFormatPAlpha or PixelFormatGDI)
PixelFormat48bppRGB = (12 or (48 shl 8) or PixelFormatExtended)
PixelFormat64bppARGB = (13 or (64 shl 8) or PixelFormatAlpha or PixelFormatCanonical or PixelFormatExtended)
PixelFormat64bppPARGB = (14 or (64 shl 8) or PixelFormatAlpha or PixelFormatPAlpha or PixelFormatExtended)
PixelFormat32bppCMYK = (15 or (32 shl 8))
PixelFormatMax = 16

PaletteTypeCustom = 0
PaletteTypeOptimal = 1
PaletteTypeFixedBW = 2
PaletteTypeFixedHalftone8 = 3
PaletteTypeFixedHalftone27 = 4
PaletteTypeFixedHalftone64 = 5
PaletteTypeFixedHalftone125 = 6
PaletteTypeFixedHalftone216 = 7
PaletteTypeFixedHalftone252 = 8
PaletteTypeFixedHalftone256 = 9

DitherTypeNone = 0
DitherTypeSolid = 1
DitherTypeOrdered4x4 = 2
DitherTypeOrdered8x8 = 3
DitherTypeOrdered16x16 = 4
DitherTypeSpiral4x4 = 5
DitherTypeSpiral8x8 = 6
DitherTypeDualSpiral4x4 = 7
DitherTypeDualSpiral8x8 = 8
DitherTypeErrorDiffusion = 9
DitherTypeMax = 10

PaletteFlagsHasAlpha = 1
PaletteFlagsGrayScale = 2
PaletteFlagsHalftone = 4

struct ColorPalette
       Flags dd ?
       Count dd ?
       Entries dd ?
ends

;Module Name:  GdiplusColor.h
;Abstract:     GDI+ Color Object

ColorModeARGB32 = 0
ColorModeARGB64 = 1

ColorChannelFlagsC = 0
ColorChannelFlagsM = 1
ColorChannelFlagsY = 2
ColorChannelFlagsK = 3
ColorChannelFlagsLast = 4

AliceBlue = $FFF0F8FF
AntiqueWhite = $FFFAEBD7
Aqua = $FF00FFFF
Aquamarine = $FF7FFFD4
Azure = $FFF0FFFF
Beige = $FFF5F5DC
Bisque = $FFFFE4C4
Black = $FF000000
BlanchedAlmond = $FFFFEBCD
Blue = $FF0000FF
BlueViolet = $FF8A2BE2
Brown = $FFA52A2A
BurlyWood = $FFDEB887
CadetBlue = $FF5F9EA0
Chartreuse = $FF7FFF00
Chocolate = $FFD2691E
Coral = $FFFF7F50
CornflowerBlue = $FF6495ED
Cornsilk = $FFFFF8DC
Crimson = $FFDC143C
Cyan = $FF00FFFF
DarkBlue = $FF00008B
DarkCyan = $FF008B8B
DarkGoldenrod = $FFB8860B
DarkGray = $FFA9A9A9
DarkGreen = $FF006400
DarkKhaki = $FFBDB76B
DarkMagenta = $FF8B008B
DarkOliveGreen = $FF556B2F
DarkOrange = $FFFF8C00
DarkOrchid = $FF9932CC
DarkRed = $FF8B0000
DarkSalmon = $FFE9967A
DarkSeaGreen = $FF8FBC8B
DarkSlateBlue = $FF483D8B
DarkSlateGray = $FF2F4F4F
DarkTurquoise = $FF00CED1
DarkViolet = $FF9400D3
DeepPink = $FFFF1493
DeepSkyBlue = $FF00BFFF
DimGray = $FF696969
DodgerBlue = $FF1E90FF
Firebrick = $FFB22222
FloralWhite = $FFFFFAF0
ForestGreen = $FF228B22
Fuchsia = $FFFF00FF
Gainsboro = $FFDCDCDC
GhostWhite = $FFF8F8FF
Gold = $FFFFD700
Goldenrod = $FFDAA520
Gray = $FF808080
Green = $FF008000
GreenYellow = $FFADFF2F
Honeydew = $FFF0FFF0
HotPink = $FFFF69B4
IndianRed = $FFCD5C5C
Indigo = $FF4B0082
Ivory = $FFFFFFF0
Khaki = $FFF0E68C
Lavender = $FFE6E6FA
LavenderBlush = $FFFFF0F5
LawnGreen = $FF7CFC00
LemonChiffon = $FFFFFACD
LightBlue = $FFADD8E6
LightCoral = $FFF08080
LightCyan = $FFE0FFFF
LightGoldenrodYellow = $FFFAFAD2
LightGray = $FFD3D3D3
LightGreen = $FF90EE90
LightPink = $FFFFB6C1
LightSalmon = $FFFFA07A
LightSeaGreen = $FF20B2AA
LightSkyBlue = $FF87CEFA
LightSlateGray = $FF778899
LightSteelBlue = $FFB0C4DE
LightYellow = $FFFFFFE0
Lime = $FF00FF00
LimeGreen = $FF32CD32
Linen = $FFFAF0E6
Magenta = $FFFF00FF
Maroon = $FF800000
MediumAquamarine = $FF66CDAA
MediumBlue = $FF0000CD
MediumOrchid = $FFBA55D3
MediumPurple = $FF9370DB
MediumSeaGreen = $FF3CB371
MediumSlateBlue = $FF7B68EE
MediumSpringGreen = $FF00FA9A
MediumTurquoise = $FF48D1CC
MediumVioletRed = $FFC71585
MidnightBlue = $FF191970
MintCream = $FFF5FFFA
MistyRose = $FFFFE4E1
Moccasin = $FFFFE4B5
NavajoWhite = $FFFFDEAD
Navy = $FF000080
OldLace = $FFFDF5E6
Olive = $FF808000
OliveDrab = $FF6B8E23
Orange = $FFFFA500
OrangeRed = $FFFF4500
Orchid = $FFDA70D6
PaleGoldenrod = $FFEEE8AA
PaleGreen = $FF98FB98
PaleTurquoise = $FFAFEEEE
PaleVioletRed = $FFDB7093
PapayaWhip = $FFFFEFD5
PeachPuff = $FFFFDAB9
Peru = $FFCD853F
Pink = $FFFFC0CB
Plum = $FFDDA0DD
PowderBlue = $FFB0E0E6
Purple = $FF800080
Red = $FFFF0000
RosyBrown = $FFBC8F8F
RoyalBlue = $FF4169E1
SaddleBrown = $FF8B4513
Salmon = $FFFA8072
SandyBrown = $FFF4A460
SeaGreen = $FF2E8B57
SeaShell = $FFFFF5EE
Sienna = $FFA0522D
Silver = $FFC0C0C0
SkyBlue = $FF87CEEB
SlateBlue = $FF6A5ACD
SlateGray = $FF708090
Snow = $FFFFFAFA
SpringGreen = $FF00FF7F
SteelBlue = $FF4682B4
Tan = $FFD2B48C
Teal = $FF008080
Thistle = $FFD8BFD8
Tomato = $FFFF6347
Transparent = $FFFFFF
Turquoise = $FF40E0D0
Violet = $FFEE82EE
Wheat = $FFF5DEB3
White = $FFFFFFFF
WhiteSmoke = $FFF5F5F5
Yellow = $FFFFFF00
YellowGreen = $FF9ACD32

AlphaShift = 24
RedShift = 16
GreenShift = 8
BlueShift = 0

AlphaMask   = $ff000000
RedMask     = $ff0000
GreenMask   = $ff00
BlueMask    = $ff

struct Color
       Argb dd ?
ends

;Module Name:  Metafile headers
;Abstract:     GDI+ Metafile Related Structures

struct ENHMETAHEADER3
       iType dd ?
       nSize dd ?
       rclBounds RECTL
       rclFrame RECTL
       dSignature dd ?
       nVersion dd ?
       nBytes dd ?
       nRecords dd ?
       nHandles dw ?
       sReserved dw ?
       nDescription dd ?
       offDescription dd ?
       nPalEntries dd ?
       szlDevice SIZEL
       szlMillimeters SIZEL
ends

struct PWMFRect16
       Left dw ?
       Top dw ?
       Right dw ?
       Bottom dw ?
ends

struct WmfPlaceableFileHeader
       Key dd ?
       Hmf dw ?
       BoundingBox PWMFRect16
       Inch dw ?
       Reserved dd ?
       Checksum dw ?
ends

GDIP_EMFPLUSFLAGS_DISPLAY = 1

struct MetafileHeader
       Type dd ?
       Size dd ?
       Version dd ?
       EmfPlusFlags dd ?
       DpiX dd ?
       DpiY dd ?
       X dd ?
       Y dd ?
       Width dd ?
       Height dd ?
       union
	   WmfHeader METAHEADER
	   EmfHeader ENHMETAHEADER3
       ends
       EmfPlusHeaderSize dd ?
       LogicalDpiX dd ?
       LogicalDpiY dd ?
ends

;Module Name:  GdiplusImaging.h

interface IImageBytes,\
	  QueryInterface,\
	  AddRef,\
	  Release,\
	  CountBytes,\
	  LockBytes,\
	  UnlockBytes

struct ImageCodecInfo
       Clsid GUID
       FormatID GUID
       CodecName dq ?
       DllName dq ?
       FormatDescription dq ?
       FilenameExtension dq ?
       MimeType dq ?
       Flags dd ?
       Version dd ?
       SigCount dd ?
       SigSize dd ?
       SigPattern dq ?
       SigMask dq ?
ends

ImageCodecFlagsEncoder = 1
ImageCodecFlagsDecoder = 2
ImageCodecFlagsSupportBitmap = 4
ImageCodecFlagsSupportVector = 8
ImageCodecFlagsSeekableEncode = $10
ImageCodecFlagsBlockingDecode = $20
ImageCodecFlagsBuiltin = $10000
ImageCodecFlagsSystem = $20000
ImageCodecFlagsUser = $40000

ImageLockModeRead = 1
ImageLockModeWrite = 2
ImageLockModeUserInputBuf = 4

struct BitmapData
       Width dd ?
       Height dd ?
       Stride dd ?
       PixelFormat dd ?
       Scan0 dq ?
       Reserved dq ?
ends

ImageFlagsNone = 0
ImageFlagsScalable = 1
ImageFlagsHasAlpha = 2
ImageFlagsHasTranslucent = 4
ImageFlagsPartiallyScalable = 8
ImageFlagsColorSpaceRGB = $10
ImageFlagsColorSpaceCMYK = $20
ImageFlagsColorSpaceGRAY = $40
ImageFlagsColorSpaceYCBCR = $80
ImageFlagsColorSpaceYCCK  = $100
ImageFlagsHasRealDPI = $1000
ImageFlagsHasRealPixelSize = $2000
ImageFlagsReadOnly = $10000
ImageFlagsCaching = $20000

RotateNoneFlipNone = 0
Rotate90FlipNone = 1
Rotate180FlipNone = 2
Rotate270FlipNone = 3
RotateNoneFlipX = 4
Rotate90FlipX = 5
Rotate180FlipX = 6
Rotate270FlipX = 7
RotateNoneFlipY = Rotate180FlipX
Rotate90FlipY = Rotate270FlipX
Rotate180FlipY = RotateNoneFlipX
Rotate270FlipY = Rotate90FlipX
RotateNoneFlipXY = Rotate180FlipNone
Rotate90FlipXY = Rotate270FlipNone
Rotate180FlipXY = RotateNoneFlipNone
Rotate270FlipXY = Rotate90FlipNone

struct EncoderParameter
       Guid GUID
       NumberOfValues dd ?
       Type dd ?
       Value dq ?
ends

struct EncoderParameters
       Count dd ?,?
       Parameter EncoderParameter
ends

ItemDataPositionAfterHeader = 0
ItemDataPositionAfterPalette = 1
ItemDataPositionAfterBits = 2

struct ImageItemData
       Size dd ?
       Position dd ?
       Desc dq ?
       DescSize dd ?,?
       Data dq ?
       DataSize dd ?
       Cookie dd ?
ends

struct PropertyItem
       id dd ?
       length dd ?
       type dw ?,?,?,?
       value dq ?
ends

PropertyTagTypeByte = 1
PropertyTagTypeASCII = 2
PropertyTagTypeShort = 3
PropertyTagTypeLong = 4
PropertyTagTypeRational = 5
PropertyTagTypeUndefined = 7
PropertyTagTypeSLONG = 9
PropertyTagTypeSRational = 10
PropertyTagExifIFD = $8769
PropertyTagGpsIFD = $8825
PropertyTagNewSubfileType = $FE
PropertyTagSubfileType = $FF
PropertyTagImageWidth = $100
PropertyTagImageHeight = $101
PropertyTagBitsPerSample = $102
PropertyTagCompression = $103
PropertyTagPhotometricInterp = $106
PropertyTagThreshHolding = $107
PropertyTagCellWidth = $108
PropertyTagCellHeight = $109
PropertyTagFillOrder = $10A
PropertyTagDocumentName = $10D
PropertyTagImageDescription = $10E
PropertyTagEquipMake = $10F
PropertyTagEquipModel = $110
PropertyTagStripOffsets = $111
PropertyTagOrientation = $112
PropertyTagSamplesPerPixel = $115
PropertyTagRowsPerStrip = $116
PropertyTagStripBytesCount = $117
PropertyTagMinSampleValue = $118
PropertyTagMaxSampleValue = $119
PropertyTagXResolution = $11A
PropertyTagYResolution = $11B
PropertyTagPlanarConfig = $11C
PropertyTagPageName = $11D
PropertyTagXPosition = $11E
PropertyTagYPosition = $11F
PropertyTagFreeOffset = $120
PropertyTagFreeByteCounts = $121
PropertyTagGrayResponseUnit = $122
PropertyTagGrayResponseCurve = $123
PropertyTagT4Option = $124
PropertyTagT6Option = $125
PropertyTagResolutionUnit = $128
PropertyTagPageNumber = $129
PropertyTagTransferFuncition = $12D
PropertyTagSoftwareUsed = $131
PropertyTagDateTime = $132
PropertyTagArtist = $13B
PropertyTagHostComputer = $13C
PropertyTagPredictor = $13D
PropertyTagWhitePoint = $13E
PropertyTagPrimaryChromaticities = $13F
PropertyTagColorMap = $140
PropertyTagHalftoneHints = $141
PropertyTagTileWidth = $142
PropertyTagTileLength = $143
PropertyTagTileOffset = $144
PropertyTagTileByteCounts = $145
PropertyTagInkSet = $14C
PropertyTagInkNames = $14D
PropertyTagNumberOfInks = $14E
PropertyTagDotRange = $150
PropertyTagTargetPrinter = $151
PropertyTagExtraSamples = $152
PropertyTagSampleFormat = $153
PropertyTagSMinSampleValue = $154
PropertyTagSMaxSampleValue = $155
PropertyTagTransferRange = $156
PropertyTagJPEGProc = $200
PropertyTagJPEGInterFormat = $201
PropertyTagJPEGInterLength = $202
PropertyTagJPEGRestartInterval = $203
PropertyTagJPEGLosslessPredictors = $205
PropertyTagJPEGPointTransforms = $206
PropertyTagJPEGQTables = $207
PropertyTagJPEGDCTables = $208
PropertyTagJPEGACTables = $209
PropertyTagYCbCrCoefficients = $211
PropertyTagYCbCrSubsampling = $212
PropertyTagYCbCrPositioning = $213
PropertyTagREFBlackWhite = $214
PropertyTagICCProfile = $8773
PropertyTagGamma = $301
PropertyTagICCProfileDescriptor = $302
PropertyTagSRGBRenderingIntent = $303
PropertyTagImageTitle = $320

PropertyTagCopyright = $8298

PropertyTagResolutionXUnit = $5001
PropertyTagResolutionYUnit = $5002
PropertyTagResolutionXLengthUnit = $5003
PropertyTagResolutionYLengthUnit = $5004
PropertyTagPrintFlags = $5005
PropertyTagPrintFlagsVersion = $5006
PropertyTagPrintFlagsCrop = $5007
PropertyTagPrintFlagsBleedWidth = $5008
PropertyTagPrintFlagsBleedWidthScale = $5009
PropertyTagHalftoneLPI = $500A
PropertyTagHalftoneLPIUnit = $500B
PropertyTagHalftoneDegree = $500C
PropertyTagHalftoneShape = $500D
PropertyTagHalftoneMisc = $500E
PropertyTagHalftoneScreen = $500F
PropertyTagJPEGQuality = $5010
PropertyTagGridSize = $5011
PropertyTagThumbnailFormat = $5012
PropertyTagThumbnailWidth = $5013
PropertyTagThumbnailHeight = $5014
PropertyTagThumbnailColorDepth = $5015
PropertyTagThumbnailPlanes = $5016
PropertyTagThumbnailRawBytes = $5017
PropertyTagThumbnailSize = $5018
PropertyTagThumbnailCompressedSize = $5019
PropertyTagColorTransferFunction = $501A
PropertyTagThumbnailData = $501B
PropertyTagThumbnailImageWidth = $5020
PropertyTagThumbnailImageHeight = $5021
PropertyTagThumbnailBitsPerSample = $5022
PropertyTagThumbnailCompression = $5023
PropertyTagThumbnailPhotometricInterp = $5024
PropertyTagThumbnailImageDescription = $5025
PropertyTagThumbnailEquipMake = $5026
PropertyTagThumbnailEquipModel = $5027
PropertyTagThumbnailStripOffsets = $5028
PropertyTagThumbnailOrientation = $5029
PropertyTagThumbnailSamplesPerPixel = $502A
PropertyTagThumbnailRowsPerStrip = $502B
PropertyTagThumbnailStripBytesCount = $502C
PropertyTagThumbnailResolutionX = $502D
PropertyTagThumbnailResolutionY = $502E
PropertyTagThumbnailPlanarConfig = $502F
PropertyTagThumbnailResolutionUnit = $5030
PropertyTagThumbnailTransferFunction = $5031
PropertyTagThumbnailSoftwareUsed = $5032
PropertyTagThumbnailDateTime = $5033
PropertyTagThumbnailArtist = $5034
PropertyTagThumbnailWhitePoint = $5035
PropertyTagThumbnailPrimaryChromaticities = $5036
PropertyTagThumbnailYCbCrCoefficients = $5037
PropertyTagThumbnailYCbCrSubsampling = $5038
PropertyTagThumbnailYCbCrPositioning = $5039
PropertyTagThumbnailRefBlackWhite = $503A
PropertyTagThumbnailCopyRight = $503B
PropertyTagLuminanceTable = $5090
PropertyTagChrominanceTable = $5091
PropertyTagFrameDelay = $5100
PropertyTagLoopCount = $5101
PropertyTagGlobalPalette = $5102
PropertyTagIndexBackground = $5103
PropertyTagIndexTransparent = $5104
PropertyTagPixelUnit = $5110
PropertyTagPixelPerUnitX = $5111
PropertyTagPixelPerUnitY = $5112
PropertyTagPaletteHistogram = $5113

PropertyTagExifExposureTime = $829A
PropertyTagExifFNumber = $829D
PropertyTagExifExposureProg = $8822
PropertyTagExifSpectralSense = $8824
PropertyTagExifISOSpeed = $8827
PropertyTagExifOECF = $8828

PropertyTagExifVer = $9000
PropertyTagExifDTOrig = $9003
PropertyTagExifDTDigitized = $9004
PropertyTagExifCompConfig = $9101
PropertyTagExifCompBPP = $9102
PropertyTagExifShutterSpeed = $9201
PropertyTagExifAperture = $9202
PropertyTagExifBrightness = $9203
PropertyTagExifExposureBias = $9204
PropertyTagExifMaxAperture = $9205
PropertyTagExifSubjectDist = $9206
PropertyTagExifMeteringMode = $9207
PropertyTagExifLightSource = $9208
PropertyTagExifFlash = $9209
PropertyTagExifFocalLength = $920A
PropertyTagExifSubjectArea = $9214
PropertyTagExifMakerNote = $927C
PropertyTagExifUserComment = $9286
PropertyTagExifDTSubsec = $9290
PropertyTagExifDTOrigSS = $9291
PropertyTagExifDTDigSS = $9292

PropertyTagExifFPXVer = $A000
PropertyTagExifColorSpace = $A001
PropertyTagExifPixXDim = $A002
PropertyTagExifPixYDim = $A003
PropertyTagExifRelatedWav = $A004
PropertyTagExifInterop = $A005
PropertyTagExifFlashEnergy  = $A20B
PropertyTagExifSpatialFR = $A20C
PropertyTagExifFocalXRes = $A20E
PropertyTagExifFocalYRes = $A20F
PropertyTagExifFocalResUnit = $A210
PropertyTagExifSubjectLoc = $A214
PropertyTagExifExposureIndex = $A215
PropertyTagExifSensingMethod = $A217
PropertyTagExifFileSource = $A300
PropertyTagExifSceneType = $A301
PropertyTagExifCfaPattern = $A302
PropertyTagExifCustomRendered = $A401
PropertyTagExifExposureMode = $A402
PropertyTagExifWhiteBalance = $A403
PropertyTagExifDigitalZoomRatio = $A404
PropertyTagExifFocalLengthIn35mmFilm = $A405
PropertyTagExifSceneCaptureType = $A406
PropertyTagExifGainControl = $A407
PropertyTagExifContrast = $A408
PropertyTagExifSaturation = $A409
PropertyTagExifSharpness = $A40A
PropertyTagExifDeviceSettingDesc = $A40B
PropertyTagExifSubjectDistanceRange = $A40C
PropertyTagExifUniqueImageID = $A420

PropertyTagGpsVer = 0
PropertyTagGpsLatitudeRef = 1
PropertyTagGpsLatitude = 2
PropertyTagGpsLongitudeRef = 3
PropertyTagGpsLongitude = 4
PropertyTagGpsAltitudeRef = 5
PropertyTagGpsAltitude = 6
PropertyTagGpsGpsTime = 7
PropertyTagGpsGpsSatellites = 8
PropertyTagGpsGpsStatus = 9
PropertyTagGpsGpsMeasureMode  = $A
PropertyTagGpsGpsDop = $B
PropertyTagGpsSpeedRef = $C
PropertyTagGpsSpeed = $D
PropertyTagGpsTrackRef = $E
PropertyTagGpsTrack = $F
PropertyTagGpsImgDirRef = $10
PropertyTagGpsImgDir = $11
PropertyTagGpsMapDatum = $12
PropertyTagGpsDestLatRef = $13
PropertyTagGpsDestLat = $14
PropertyTagGpsDestLongRef = $15
PropertyTagGpsDestLong = $16
PropertyTagGpsDestBearRef = $17
PropertyTagGpsDestBear = $18
PropertyTagGpsDestDistRef = $19
PropertyTagGpsDestDist = $1A
PropertyTagGpsProcessingMethod = $1B
PropertyTagGpsAreaInformation = $1C
PropertyTagGpsDate = $1D
PropertyTagGpsDifferential = $1E

;Module Name:   GdiplusColorMatrix.h
;Abstract:      GDI+ Color Matrix object, used with Graphics.DrawImage

;typedef BYTE ColorChannelLUT[256];

HistogramFormatARGB = 0
HistogramFormatPARGB = 1
HistogramFormatRGB = 2
HistogramFormatGray = 3
HistogramFormatB = 4
HistogramFormatG = 5
HistogramFormatR = 6
HistogramFormatA = 7

struct ColorMatrix
       m dd 5*5 dup(?)
ends

ColorMatrixFlagsDefault = 0
ColorMatrixFlagsSkipGrays = 1
ColorMatrixFlagsAltGray = 2

ColorAdjustTypeDefault = 0
ColorAdjustTypeBitmap = 1
ColorAdjustTypeBrush = 2
ColorAdjustTypePen = 3
ColorAdjustTypeText = 4
ColorAdjustTypeCount = 5
ColorAdjustTypeAny = 6

struct ColorMap
       oldColor dd ?
       newColor dd ?
ends

;GdiplusEffects
;Module Name: Gdiplus effect objects.
;Created: 05/29/2001 asecchia Created it.

struct SharpenParams
       radius dd ?
       amount dd ?
ends

struct BlurParams
       radius dd ?
       expandEdge dd ?
ends

struct BrightnessContrastParams
       brightnessLevel dd ?
       contrastLevel dd ?
ends

struct RedEyeCorrectionParams
       numberOfAreas dd ?,?
       areas dq ?
ends

struct HueSaturationLightnessParams
       hueLevel dd ?
       saturationLevel dd ?
       lightnessLevel dd ?
ends

struct TintParams
       hue dd ?
       amount dd ?
ends

struct LevelsParams
       highlight dd ?
       midtone dd ?
       shadow dd ?
ends

struct ColorBalanceParams
       cyanRed dd ?
       magentaGreen dd ?
       yellowBlue dd ?
ends

struct ColorLUTParams
       lutB db 256 dup(?)
       lutG db 256 dup(?)
       lutR db 256 dup(?)
       lutA db 256 dup(?)
ends

AdjustExposure = 0
AdjustDensity = 1
AdjustContrast = 2
AdjustHighlight = 3
AdjustShadow = 4
AdjustMidtone = 5
AdjustWhiteSaturation = 6
AdjustBlackSaturation = 7

CurveChannelAll = 0
CurveChannelRed = 1
CurveChannelGreen = 2
CurveChannelBlue = 3

struct ColorCurveParams
       adjustment dd ?
       channel dd ?
       adjustValue dd ?
ends

struct Effect
       nativeGraphics dq ?
       nativeEffect dq ?
       auxDataSize dd ?,?
       auxData dq ?
       useAuxData dd ?,?
ends


